const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('flowAPI', {
  openFile: (opts) => ipcRenderer.invoke('dialog:openFile', opts),
  openPath: (p) => ipcRenderer.invoke('shell:openPath', p),
  status: () => ipcRenderer.invoke('flow:status'),
  ensureCdp: () => ipcRenderer.invoke('flow:ensureCdp'),
  openProfileLogin: (profile, idx) => ipcRenderer.invoke('flow:openProfileLogin', profile, idx),
  start: (payload) => ipcRenderer.invoke('flow:start', payload),
  pause: () => ipcRenderer.invoke('flow:pause'),
  resume: () => ipcRenderer.invoke('flow:resume'),
  stop: () => ipcRenderer.invoke('flow:stop'),
  licenseCheck: () => ipcRenderer.invoke('license:check'),
  licenseCached: () => ipcRenderer.invoke('license:cached'),
  machineId: () => ipcRenderer.invoke('license:machineId'),
  activateLicense: (payload) => ipcRenderer.invoke('license:activate', payload),
  generatePrompt: (payload) => ipcRenderer.invoke('prompt:generate', payload),
  generateScript: (payload) => ipcRenderer.invoke('prompt:script', payload),
  videoList: (folder) => ipcRenderer.invoke('video:list', folder),
  videoMerge: (payload) => ipcRenderer.invoke('video:merge', payload),
  videoExtractAudio: (payload) => ipcRenderer.invoke('video:extractAudio', payload),
  videoAnalyze: (payload) => ipcRenderer.invoke('video:analyze', payload),
  videoExportTimeline: (payload) => ipcRenderer.invoke('video:exportTimeline', payload),
  videoAnalyzeSample: (payload) => ipcRenderer.invoke('video:analyzeSample', payload),
});
