name: Build FlowAuto Electron macOS
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: cd apps/flow_auto_electron && npm install
      - name: Build macOS App
        run: cd apps/flow_auto_electron && npm run dist
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: FlowAuto-Electron-MacOS
          path: apps/flow_auto_electron/release/*.dmg
